apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: viroonga-wp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: viroonga-wp
    spec:
      containers:
      - name: viroonga-wp
        image: wordpress:latest
        volumeMounts:
        - mountPath: "/var/www/html"
          name: viroonga-wp-vol
        env:
        - name: WORDPRESS_DB_HOST
          value: "127.0.0.1:3306"
        - name: WORDPRESS_DB_NAME
          value: "viroongawp"
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "250m"
      - image: gcr.io/cloudsql-docker/gce-proxy:1.09
        name: cloudsql-proxy
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        command: ["/cloud_sql_proxy", "--dir=/cloudsql",
                    "-instances=cloud-ninjaio:us-central1:cloud-ninja=tcp:3306",
                    "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql
              readOnly: true
            - name: ssl-certs
              mountPath: /etc/ssl/certs
            - name: cloudsql
              mountPath: /cloudsql
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
        - name: ssl-certs
          hostPath:
            path: /etc/ssl/certs
        - name: cloudsql
          emptyDir:
        - name: viroonga-wp-vol
          persistentVolumeClaim:
            claimName: viroonga-wp-pvc